---
- name: configure wifi country
  command: raspi-config nonint do_wifi_country FR

- name: configure wlan0
  template:
    src: templates/projector/wlan0.j2
    dest: /etc/network/interfaces.d/wlan0
    mode: 0600