---
- name: install packages
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - hostapd
    - isc-dhcp-server

- name: configure hostapd default
  lineinfile:
    dest: /etc/default/hostapd
    line: DAEMON_CONF="/etc/hostapd/hostapd.conf"
    regexp: ^DAEMON_CONF=

- name: create hostapd configuration
  template:
    src: templates/photobooth/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0600

- name: configure timezone
  command: raspi-config nonint do_change_timezone Europe/Paris

<<<<<<< HEAD
- name: configure i2c
  command: raspi-config nonint do_i2c 0

=======
>>>>>>> Initial commit
- name: update /boot/config.txt for ds3231 RTC module support
  lineinfile:
    dest: /boot/config.txt
    line: dtoverlay=i2c-rtc,ds3231

<<<<<<< HEAD
- name: update /lib/udev/hwclock-set
  blockinfile:
    path: /lib/udev/hwclock-set
    block: |
      if [ -e /run/systemd/system ] ; then
          exit 0
      fi
    state: absent

=======
>>>>>>> Initial commit
- name: configure wlan0
  copy:
    src: files/photobooth/wlan0
    dest: /etc/network/interfaces.d/wlan0

- name: configure dhcpd for wlan0
  copy:
    src: files/photobooth/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf

