- hosts: projector
  vars:
    feh_version: feh-2.24
    feh_source: http://feh.finalrewind.org/{{feh_version}}.tar.bz2
    feh_config:
      reload: 5
      delay: 5
      path: /root/slideshow
  tasks:
    - name: install packages
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - inotify-tools
        - xorg
        - libcurl4-openssl-dev
        - libx11-dev
        - libxt-dev
        - libimlib2-dev
        - libxinerama-dev
        - libjpeg-progs
        - build-essential
        - firmware-zd1211
        - wpasupplicant
    - name: create feh unarchive directory
      file:
        path: /tmp/{{feh_version}}
        state: directory
    - name: download feh
      unarchive:
        src: "{{feh_source}}"
        dest: /tmp/{{feh_version}}
        remote_src: yes
        extra_opts:
          - "--strip-components=1"
        creates: /tmp/{{feh_version}}/Makefile
    - name: install feh
      shell: make && make install
      args:
        chdir: /tmp/{{feh_version}}
        creates: /usr/local/bin/feh
    - name: create slideshow directory
      file:
        path: "{{feh_config.path}}"
        state: directory
    - name: copy default slideshow image
      copy:
        src: files/projector/default.jpg
        dest: "{{feh_config.path}}"
    - name: deploy root xinitrc
      template:
        src: templates/projector/xinitrc.j2
        dest: /root/.xinitrc
        owner: root
        group: root
        mode: 0644

- hosts: photobooth
  tasks:
    - name: install packages
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - imagemagick
        - python-dev
        - build-essential
        - python-pkgconfig
        - python-setuptools
        - hostapd
        - virtualenv
    - name: install pip packages
      pip:
        name: "{{item}}"
        virtualenv: /root/.venv_photobooth
      with_items:
        - RPi.GPIO
        - gphoto2


- hosts: all
  vars:
    wifi_ssid: ssid
    wifi_passphrase: changeme
  tasks:
    - name: set hostname
      hostname:
        name: "{{inventory_hostname}}"
    - name: update /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{item}}"
      with_items:
        - 10.200.0.1 projector
        - 10.200.0.2 photobooth
    - name: deploy autologin unit
      copy:
        src: /lib/systemd/system/getty@.service
        dest: /etc/systemd/system/autologin@.service
        remote_src: yes
    - name: update autologin unit
      lineinfile:
        dest: /etc/systemd/system/autologin@.service
        line: ExecStart=-/sbin/agetty -a root %I $TERM
        regexp: ^ExecStart=-/sbin/agetty
    - name: Disable tty1 unit
      systemd:
        daemon_reload: yes
        enabled: no
        name: getty@tty1.service
    - name: Enable autologin unit
      systemd:
        daemon_reload: yes
        enabled: yes
        state: restarted
        name: autologin@tty1.service
    - name: copy bash_profile
      copy:
        src: files/projector/bash_profile
        dest: /root/.bash_profile
        owner: root
        group: root
        mode : 0644
    - name: is raspberry
      stat:
        path: /boot/cmdline.txt
      register: israspeberry
    - name: setup raspberry for {{inventory_hostname}}
      include_tasks: raspberry-{{inventory_hostname}}-setup.yml
      when: israspeberry.stat.exists
